// Generated by Haxe 4.3.3
(function ($global) { "use strict";
var HxOverrides = function() { };
HxOverrides.substr = function(s,pos,len) {
	if(len == null) {
		len = s.length;
	} else if(len < 0) {
		if(pos == 0) {
			len = s.length + len;
		} else {
			return "";
		}
	}
	return s.substr(pos,len);
};
HxOverrides.now = function() {
	return Date.now();
};
var Main = function() { };
Main.main = function() {
	var canvas = window.document.getElementById("c");
	canvas.width = 640;
	canvas.height = 240;
	Main.ctx = canvas.getContext("2d",null);
	Main.beep = new Audio("Beep.wav");
	Main.beep.volume = 0.5;
	window.addEventListener("keydown",Main.onKeyDown);
	window.requestAnimationFrame(Main.loop);
};
Main.onKeyDown = function(e) {
	if(e.key.toLowerCase() == "z") {
		var currentText = Main.messages[Main.msgIndex];
		if(Main.charIndex < currentText.length) {
			Main.charIndex = currentText.length;
			Main.isFinished = true;
		} else if(Main.msgIndex < Main.messages.length - 1) {
			Main.msgIndex++;
			Main.charIndex = 0;
			Main.isFinished = false;
		}
	}
};
Main.loop = function(t) {
	Main.timer += 0.016;
	if(Main.timer >= Main.speed && Main.charIndex < Main.messages[Main.msgIndex].length) {
		var char = Main.messages[Main.msgIndex].charAt(Main.charIndex);
		Main.charIndex++;
		Main.timer = 0;
		if(char != " " && char != "\n") {
			Main.playBeep();
		}
		if(Main.charIndex == Main.messages[Main.msgIndex].length) {
			Main.isFinished = true;
		}
	}
	Main.draw();
	window.requestAnimationFrame(Main.loop);
};
Main.playBeep = function() {
	if(Main.beep != null) {
		Main.beep.pause();
		Main.beep.currentTime = 0;
		Main.beep.play().catch(function(e) {
		});
	}
};
Main.draw = function() {
	Main.ctx.fillStyle = "#000";
	Main.ctx.fillRect(0,0,640,240);
	Main.ctx.strokeStyle = "#fff";
	Main.ctx.lineWidth = 4;
	Main.ctx.strokeRect(10,10,620,220);
	Main.ctx.font = "24px 'Courier New', monospace";
	Main.ctx.fillStyle = "#fff";
	var lines = HxOverrides.substr(Main.messages[Main.msgIndex],0,Main.charIndex).split("\n");
	var _g = 0;
	var _g1 = lines.length;
	while(_g < _g1) {
		var i = _g++;
		var line = lines[i];
		var _g2 = 0;
		var _g3 = line.length;
		while(_g2 < _g3) {
			var j = _g2++;
			var char = line.charAt(j);
			var offsetX = Math.random() * 2 - 1;
			var offsetY = Math.random() * 2 - 1;
			Main.ctx.fillText(char,40 + j * 16 + offsetX,60 + i * 40 + offsetY);
		}
	}
	if(Main.isFinished && Math.floor(new Date().getTime() / 500) % 2 == 0) {
		Main.ctx.fillText("▼",580,200);
	}
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
if(typeof(performance) != "undefined" ? typeof(performance.now) == "function" : false) {
	HxOverrides.now = performance.now.bind(performance);
}
Main.messages = ["こんにちは！\nこれはUNDERTALE風のHaxeエンジンだよ。","Zキーを押すと、文字を一気に表示したり\n次のセリフに進んだりできるよ。","文字を揺らしたりできるよ！"];
Main.msgIndex = 0;
Main.charIndex = 0;
Main.timer = 0;
Main.speed = 0.05;
Main.isFinished = false;
Main.main();
})({});
