// Generated by Haxe 4.3.3
(function ($global) { "use strict";
var HxOverrides = function() { };
HxOverrides.substr = function(s,pos,len) {
	if(len == null) {
		len = s.length;
	} else if(len < 0) {
		if(pos == 0) {
			len = s.length + len;
		} else {
			return "";
		}
	}
	return s.substr(pos,len);
};
HxOverrides.now = function() {
	return Date.now();
};
var Main = function() { };
Main.main = function() {
	Main.ctx = window.document.getElementById("c").getContext("2d",null);
	window.requestAnimationFrame(Main.loop);
};
Main.loop = function(t) {
	Main.timer += 0.016;
	if(Main.timer >= Main.speed && Main.index < Main.text.length) {
		Main.index++;
		Main.timer = 0;
	}
	Main.draw();
	window.requestAnimationFrame(Main.loop);
};
Main.draw = function() {
	Main.ctx.fillStyle = "#000";
	Main.ctx.fillRect(0,0,800,200);
	Main.ctx.font = "24px JetBrains Mono";
	Main.ctx.fillStyle = "#fff";
	var lines = HxOverrides.substr(Main.text,0,Main.index).split("\n");
	var _g = 0;
	var _g1 = lines.length;
	while(_g < _g1) {
		var i = _g++;
		var offsetX = 0;
		var offsetY = 0;
		if(Main.shake) {
			offsetX = Std.random(3) - 1;
			offsetY = Std.random(3) - 1;
		}
		Main.ctx.fillText(lines[i],20 + offsetX,40 + i * 30 + offsetY);
	}
};
var Std = function() { };
Std.random = function(x) {
	if(x <= 0) {
		return 0;
	} else {
		return Math.floor(Math.random() * x);
	}
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
if(typeof(performance) != "undefined" ? typeof(performance.now) == "function" : false) {
	HxOverrides.now = performance.now.bind(performance);
}
Main.text = "こんにちは\nこれはUNDERTALE風のHaxe対話エンジンだよ。";
Main.index = 0;
Main.timer = 0;
Main.speed = 0.03;
Main.shake = false;
Main.main();
})({});
