// Generated by Haxe 4.3.3
(function ($global) { "use strict";
var HxOverrides = function() { };
HxOverrides.substr = function(s,pos,len) {
	if(len == null) {
		len = s.length;
	} else if(len < 0) {
		if(pos == 0) {
			len = s.length + len;
		} else {
			return "";
		}
	}
	return s.substr(pos,len);
};
HxOverrides.now = function() {
	return Date.now();
};
var Main = function() { };
Main.main = function() {
	var canvas = window.document.getElementById("c");
	canvas.width = 640;
	canvas.height = 240;
	Main.ctx = canvas.getContext("2d",null);
	window.addEventListener("keydown",Main.onKeyDown);
	window.addEventListener("keyup",function(_) {
		return Main.isKeyPressed = false;
	});
	window.addEventListener("mousedown",Main.initAudio);
	window.requestAnimationFrame(Main.loop);
};
Main.initAudio = function(_) {
	if(Main.audioCtx == null) {
		var audioContextClass = window.AudioContext || window.webkitAudioContext;
		if(audioContextClass != null) {
			Main.audioCtx = Type.createInstance(audioContextClass,[]);
		}
	}
	if(Main.audioCtx != null && Main.audioCtx.state == "suspended") {
		Main.audioCtx.resume();
	}
};
Main.onKeyDown = function(e) {
	if(e.key.toLowerCase() == "z" && !Main.isKeyPressed) {
		Main.isKeyPressed = true;
		var current = Main.messages[Main.msgIndex];
		if(Main.charIndex < current.text.length) {
			Main.charIndex = current.text.length;
			Main.isFinished = true;
		} else if(Main.msgIndex < Main.messages.length - 1) {
			Main.msgIndex++;
			Main.charIndex = 0;
			Main.isFinished = false;
			Main.currentWait = Main.textSpeed;
		}
	}
};
Main.loop = function(t) {
	Main.timer += 0.016;
	var current = Main.messages[Main.msgIndex];
	if(!Main.isFinished && Main.timer >= Main.currentWait) {
		var char = current.text.charAt(Main.charIndex);
		Main.charIndex++;
		Main.timer = 0;
		if(char == "。" || char == "、" || char == "？" || char == "！") {
			Main.currentWait = Main.waitSpeed;
		} else {
			Main.currentWait = Main.textSpeed;
			if(char != " " && char != "　") {
				Main.playBeep();
			}
		}
		if(Main.charIndex >= current.text.length) {
			Main.isFinished = true;
		}
	}
	Main.draw();
	window.requestAnimationFrame(Main.loop);
};
Main.playBeep = function() {
	if(Main.audioCtx == null) {
		return;
	}
	var osc = Main.audioCtx.createOscillator();
	var gain = Main.audioCtx.createGain();
	osc.type = "square";
	osc.frequency.setValueAtTime(140,Main.audioCtx.currentTime);
	gain.gain.setValueAtTime(0.04,Main.audioCtx.currentTime);
	gain.gain.exponentialRampToValueAtTime(0.001,Main.audioCtx.currentTime + 0.05);
	osc.connect(gain);
	gain.connect(Main.audioCtx.destination);
	osc.start();
	osc.stop(Main.audioCtx.currentTime + 0.05);
};
Main.draw = function() {
	Main.ctx.fillStyle = "#000";
	Main.ctx.fillRect(0,0,640,240);
	Main.ctx.strokeStyle = "#fff";
	Main.ctx.lineWidth = 4;
	Main.ctx.strokeRect(10,10,620,220);
	Main.ctx.font = "22px 'Courier New', 'DotGothic16', sans-serif";
	Main.ctx.fillStyle = "#fff";
	var current = Main.messages[Main.msgIndex];
	var lines = HxOverrides.substr(current.text,0,Main.charIndex).split("\n");
	var _g = 0;
	var _g1 = lines.length;
	while(_g < _g1) {
		var i = _g++;
		var line = lines[i];
		if(current.isShake) {
			var _g2 = 0;
			var _g3 = line.length;
			while(_g2 < _g3) {
				var j = _g2++;
				var ox = Math.random() * 2 - 1;
				var oy = Math.random() * 2 - 1;
				Main.ctx.fillText(line.charAt(j),40 + j * 22 + ox,60 + i * 36 + oy);
			}
		} else {
			Main.ctx.fillText(line,40,60 + i * 36);
		}
	}
	if(Main.isFinished && Math.floor(new Date().getTime() / 500) % 2 == 0) {
		Main.ctx.fillText("▼",585,205);
	}
};
var Type = function() { };
Type.createInstance = function(cl,args) {
	var ctor = Function.prototype.bind.apply(cl,[null].concat(args));
	return new (ctor);
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
if(typeof(performance) != "undefined" ? typeof(performance.now) == "function" : false) {
	HxOverrides.now = performance.now.bind(performance);
}
Main.messages = [{ text : "これは テキスト送りの サンプルプログラムです。", isShake : false},{ text : "Zキーを押すと 次のメッセージに 進みます。", isShake : false},{ text : "揺れる演出を 入れることも 可能です！！", isShake : true},{ text : "さあ、ここから 冒険を 始めましょう。", isShake : false}];
Main.textSpeed = 0.05;
Main.waitSpeed = 0.3;
Main.msgIndex = 0;
Main.charIndex = 0;
Main.timer = 0;
Main.currentWait = 0.05;
Main.isFinished = false;
Main.isKeyPressed = false;
Main.main();
})({});
